project_name: go-short-url-server
before:
  hooks:
#  - make clean
  - go generate ./...
builds:
- main: ./cmd/server/.
  binary: go-short-url-server
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  env:
  - CGO_ENABLED=0

archive:
  replacements:
    windows: Windows
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Linux
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE.md
  - README.md
